### ISSUE TITLE
Error during SonarQube Scanner execution

### ISSUE THREAD

**Issue by shivendrakd** [racodond/sonar-gherkin-plugin#74]
Looks like plugin is not compatible with the 7.9 api. Please help.
Error Logs are as follows.

17:14:56.092 DEBUG: 'MisysPD/PartyProfile/PartyProfileBusiness/src/com/misys/bf/party/profile/treasury/IPartyProfileTreasury.java' generated metadata with charset 'UTF-8'
17:14:56.098 DEBUG: 'MisysPD/PartyProfile/PartyProfileBusiness/src/com/misys/bf/party/profile/utils/PartyProfileConstants.java' generated metadata with charset 'UTF-8'
17:14:56.107 DEBUG: 'MisysPD/PartyProfile/PartyProfileBusiness/src/com/misys/bf/party/profile/utils/PartyProfileUtils.java' generated metadata with charset 'UTF-8'
17:14:56.133 INFO: 681/681 source files have been analyzed
17:14:56.134 INFO: Java Main Files AST scan (done) | time=79688ms
17:14:56.134 INFO: Java Test Files AST scan
17:14:56.134 INFO: 0 source files to be analyzed
17:14:56.135 INFO: Java Test Files AST scan (done) | time=1ms
17:14:56.135 INFO: Sensor JavaSquidSensor [java] (done) | time=80189ms
17:14:56.135 INFO: Sensor SurefireSensor [java]
17:14:56.136 INFO: 0/0 source files have been analyzed
17:14:56.136 INFO: parsing [/QuickBuildTemplates/5.3.1.2/PF/raw]
17:14:56.137 ERROR: Reports path not found or is not a directory: /QuickBuildTemplates/5.3.1.2/PF/raw
17:14:56.137 INFO: Sensor SurefireSensor [java] (done) | time=2ms
17:14:56.137 INFO: Sensor JaCoCoSensor [java]
17:14:56.137 INFO: Sensor JaCoCoSensor [java] (done) | time=0ms
17:14:56.138 INFO: Sensor JavaXmlSensor [java]
17:14:56.144 INFO: Sensor JavaXmlSensor [java] (done) | time=6ms
17:14:56.144 INFO: Sensor HTML [web]
17:14:56.156 INFO: Sensor HTML [web] (done) | time=12ms
17:14:56.156 INFO: Sensor Gherkin Squid Sensor [gherkin]
17:14:56.160 INFO: 5 source files to be analyzed
17:14:56.364 INFO: ------------------------------------------------------------------------
17:14:56.364 INFO: EXECUTION FAILURE
17:14:56.364 INFO: ------------------------------------------------------------------------
17:14:56.364 INFO: Total time: 1:28.506s
17:14:56.683 INFO: Final Memory: 70M/1979M
17:14:56.683 INFO: ------------------------------------------------------------------------
17:14:56.683 ERROR: Error during SonarQube Scanner execution
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at net.loomchild.segment.srx.io.Srx2SaxParser.<init>(Srx2SaxParser.java:173)
	at org.languagetool.tokenizers.SrxTools.createSrxDocument(SrxTools.java:51)
	at org.languagetool.tokenizers.SRXSentenceTokenizer.<init>(SRXSentenceTokenizer.java:53)
	at org.languagetool.tokenizers.SimpleSentenceTokenizer.<init>(SimpleSentenceTokenizer.java:37)
	at org.languagetool.Language.<clinit>(Language.java:60)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)

**Comment by racodond** [comment]
Hi @shivendrakd,

I don't want to keep maintaining this plugin. Feel free to ping me if you want to take over.

Regards,

David
